apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
        - name: taskmanager-container
          image: 2022cfse006/taskmanager:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "0.01"
              memory: "2Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  selector:
    app: taskmanager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taskmanager-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskmanager-service
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60 